eMotive.Site/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using eMotive.Managers.Interfaces;
using eMotive.SCE.Common.Providers;
using eMotive.Models.Objects.Certificates;
using eMotive.Models.Objects.Uploads;
using eMotive.Models.Objects.Users;
using eMotive.SCE.Infrastructure;
using eMotive.Services.Interfaces;
using Extensions;
using Newtonsoft.Json.Linq;
using OfficeOpenXml;
using Rotativa;
using ServiceStack.Mvc;

namespace eMotive.SCE.Controllers
{
    public class TestController : ServiceStackController
    {
        private readonly IUserManager userManager;
        private readonly IRoleManager rolemanager;
        private readonly IAccountManager accountManager;
        private readonly IGroupManager groupManager;
        private readonly IDocumentManagerService documentManager;
        private readonly INotificationService notificationManager;
        
        //
        // GET: /Test/
        public TestController(IUserManager _userManager, IRoleManager _rolemanager, IAccountManager _accountManager, IDocumentManagerService _documentManager, IGroupManager _groupManager, INotificationService _notificationManager)
        {
            userManager = _userManager;
            documentManager = _documentManager;
            groupManager = _groupManager;
            notificationManager = _notificationManager;
            rolemanager = _rolemanager;
            accountManager = _accountManager;
        }

        public ActionResult Index()
        {
            return View(userManager.New());
        }

        [HttpPost]
        public ActionResult Index(User user)
        {
            int id;
            if (!userManager.Create(user, out id))
            {
                var issues = notificationManager.FetchIssues();

                if(issues.HasContent())
                foreach (var message in issues)
                {
                    Response.Write(message + "<br/>");
                }
            }

            return View(user);
        }

        public ActionResult Index2()
        {
            return View(/*userManager.DoSearch(new BasicSearch {PageSize = 90})*/);
        }

        public ActionResult ModalTest()
        {
            return View();
        }

        public ActionResult UploadTest()
        {
            return View();
        }

        public ActionResult SignalRTest()
        {
            return View();
        }

        public class DictTester
        {
            public DictTester()
            {
            //    SomeStuff1 = new List<KeyValuePair<string, string>>();
                SomeStuff = new List<Field>();
                DropDowns = new Dictionary<string, List<KeyValuePair<string, string>>>();
            }

            public List<KeyValuePair<string, string>> SomeStuff1 { get; set; }
            public List<Field> SomeStuff { get; set; }

            public Dictionary<string, List<KeyValuePair<string, string>>> DropDowns { get; set; }

        }

        public enum FieldType { Text, DropDownList }

        public class Field
        {
            public FieldType Type { get; set; }
            public string Name { get; set; }
            public string Value { get; set; }
        }

        [HttpGet]
        public ActionResult DictTest()
        {
            var test = new DictTester();

            test.SomeStuff.Add(new Field { Type = FieldType.Text, Name = "Forename", Value ="Chris" });
            test.SomeStuff.Add(new Field { Type = FieldType.Text, Name = "Surname", Value = "Withers" });
            test.SomeStuff.Add(new Field { Type = FieldType.DropDownList, Name = "1", Value = "3" });
            test.SomeStuff.Add(new Field { Type = FieldType.DropDownList, Name = "2", Value = "2" });

            test.DropDowns.Add("1", new List<KeyValuePair<string, string>>());
            test.DropDowns["1"].Add(new KeyValuePair<string, string>("1", "Item 1"));
            test.DropDowns["1"].Add(new KeyValuePair<string, string>("2", "Item 2"));
            test.DropDowns["1"].Add(new KeyValuePair<string, string>("3", "Item 3"));
            test.DropDowns["1"].Add(new KeyValuePair<string, string>("4", "Item 4"));

            test.DropDowns.Add("2", new List<KeyValuePair<string, string>>());
            test.DropDowns["2"].Add(new KeyValuePair<string, string>("1", "Item 11"));
            test.DropDowns["2"].Add(new KeyValuePair<string, string>("2", "Item 22"));
            test.DropDowns["2"].Add(new KeyValuePair<string, string>("3", "Item 33"));
            test.DropDowns["2"].Add(new KeyValuePair<string, string>("4", "Item 44"));

            return View(test);
        }

        [HttpPost]
        public ActionResult DictTest(DictTester test)
        {
            test.DropDowns.Add("1", new List<KeyValuePair<string, string>>());
            test.DropDowns["1"].Add(new KeyValuePair<string, string>("1", "Item 1"));
            test.DropDowns["1"].Add(new KeyValuePair<string, string>("2", "Item 2"));
            test.DropDowns["1"].Add(new KeyValuePair<string, string>("3", "Item 3"));
            test.DropDowns["1"].Add(new KeyValuePair<string, string>("4", "Item 4"));

            test.DropDowns.Add("2", new List<KeyValuePair<string, string>>());
            test.DropDowns["2"].Add(new KeyValuePair<string, string>("1", "Item 11"));
            test.DropDowns["2"].Add(new KeyValuePair<string, string>("2", "Item 22"));
            test.DropDowns["2"].Add(new KeyValuePair<string, string>("3", "Item 33"));
            test.DropDowns["2"].Add(new KeyValuePair<string, string>("4", "Item 44"));

            return View(test);
        }



        public ActionResult BoxiUploadTest()
        {
            var applicantUploadView = new ApplicantUploadView
                {
                    Groups = groupManager.FetchGroups(),
                    LastUploadedDocument = documentManager.FetchLastUploaded(UploadReference.A100Applicants)
                };


            return View(applicantUploadView);
        }



        public class FineUploaderResult : ActionResult
        {
            public const string ResponseContentType = "text/plain";

            private readonly bool _success;
            private readonly string _error;
            private readonly bool? _preventRetry;
            private readonly JObject _otherData;

            public FineUploaderResult(bool success, object otherData = null, string error = null, bool? preventRetry = null)
            {
                _success = success;
                _error = error;
                _preventRetry = preventRetry;

                if (otherData != null)
                    _otherData = JObject.FromObject(otherData);
            }

            public override void ExecuteResult(ControllerContext context)
            {
                var response = context.HttpContext.Response;
                response.ContentType = ResponseContentType;

                response.Write(BuildResponse());
            }

            public string BuildResponse()
            {
                var response = _otherData ?? new JObject();
                response["success"] = _success;

                if (!string.IsNullOrWhiteSpace(_error))
                    response["error"] = _error;

                if (_preventRetry.HasValue)
                    response["preventRetry"] = _preventRetry.Value;

                return response.ToString();
            }
        }


        //
        // GET: /Test/Details/5
/*
        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Test/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Test/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Test/Edit/5

        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Test/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Test/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Test/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }*/

        public ActionResult SendSCEEmails()
        {
          /*  var users = userManager.FetchAll();
            var sces = users.Where(n => n.Roles.Any(r => r.Name == "SCE"));

            foreach (var p in sces)
            {
             //   Response.Write(sces.Count());
                
                accountManager.CreateNewAccountPassword(p);
            }*/
            return View();
        }



        public ActionResult PDF()
        {
            return new ActionAsPdf(
               "PDFView") { FileName = "Certificate.pdf" };
        }

        public ActionResult PDFView()
        {
            var certificate = new SCECertificate
            {
                Title = "Mr",
                Forename = "Christopher",
                Surname = "Withers",

eMotive.Site/Views/Test/AddSCEs.cshtml
@using Extensions
@model IEnumerable<eMotive.Models.Objects.Users.UserWithRoles>

@{
    ViewBag.Title = "AddSCEs";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>AddSCEs</h2>


@if (Model.HasContent())
{
    <table>
        @foreach (var user in Model)
        {
            <tr>
                <td>@user.Username</td>
                <td>@user.Forename</td>
                <td>@user.Surname</td>
                <td>@user.Email</td>
                <td>@user.Enabled</td>
                <td>@user.Archived</td>
                <td>@user.Roles.First().Name</td>
            </tr>
        }
    </table>
}

eMotive.Site/Views/Test/BoxiUploadTest.cshtml
@using eMotive.Models.Objects.Users
@model ApplicantUploadView
@{
    ViewBag.Title = "UploadTest";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<link href="~/Content/fineuploader-3.8.2.min.css" rel="stylesheet" />
  <style>
      .qq-upload-list {
        text-align: left;
      }

      /* For the bootstrapped demos */
      li.alert-success {
        background-color: #DFF0D8;
      }

      li.alert-error {
        background-color: #F2DEDE;
      }

      .alert-error .qq-upload-failed-text {
        display: inline;
      }
    </style>

<h2>UploadTest</h2>

@if (Model != null)
{
    <div class="alert alert-info">
        <h4>Last Uploaded Document</h4>
        <i>"@Model.LastUploadedDocument.Name"</i> Uploaded on @Model.LastUploadedDocument.DateUploaded.ToLongDateString() by @if (Model.LastUploadedDocument.UploadedBy != null) { Html.Raw(string.Format("{0} {1}", Model.LastUploadedDocument.UploadedBy.Forename, Model.LastUploadedDocument.UploadedBy.Surname)); }
                                                                                                                             else
                                                                                                                             { @Html.Raw(Model.LastUploadedDocument.UploadedByUsername); }
    </div>
    
    foreach (var group in Model.Groups)
    {
        <label class="checkbox">
            <input type="checkbox" name="groups" value="@group.ID"> @group.Name
        </label>

    }
}

<div id="fubErrorAlert" class="alert alert-error hide">
    <button type="button" class="close">&times;</button>
    <span class="message"></span>
</div>

<div id="fine-uploader-basic" class="btn btn-success">
  <i class="icon-upload icon-white"></i> Click to upload
</div>
<div id="messages"></div>


@section Scripts
{
    <script src="~/Scripts/fineuploader-3.8.2.min.js"></script>
    <script>
        $(document).ready(function() {
            var $fub = $('#fine-uploader-basic');
            var $messages = $('#messages');

            var uploader = new qq.FineUploaderBasic({
                button: $fub[0],
                multiple: false,
                request: {
                    endpoint: 'BoxiUploadTest',
                    params: {
                        dsfsdfds : 'sdsdfdfdfs'
                    }
                },
                validation: {
                    allowedExtensions: ['xlsx']//,
                    //   sizeLimit: 204800 // 200 kB = 200 * 1024 bytes
                },
                callbacks: {
                    onSubmit: function(id, fileName) {
                        $messages.append('<div id="file-' + id + '" class="alert" style="margin: 20px 0 0"></div>');
                    },
                    onUpload: function(id, fileName) {
                        $('#file-' + id).addClass('alert-info')
                            .html('<img src="Images/loading.gif" alt="Initializing. Please hold."> ' +
                                'Initializing ' +
                                '“' + fileName + '”');
                    },
                    onProgress: function(id, fileName, loaded, total) {
                        if (loaded < total) {
                            progress = Math.round(loaded / total * 100) + '% of ' + Math.round(total / 1024) + ' kB';
                            $('#file-' + id).removeClass('alert-info')
                                .html('<img src="Images/loading.gif" alt="In progress. Please hold."> ' +
                                    'Uploading ' +
                                    '“' + fileName + '” ' +
                                    progress);
                        } else {
                            $('#file-' + id).addClass('alert-info')
                                .html('<img src="Images/loading.gif" alt="Saving. Please hold."> ' +
                                    'Saving ' +
                                    '“' + fileName + '”');
                        }
                    },
                    onComplete: function(id, fileName, responseJSON) {
                        if (responseJSON.success) {
                            $('#file-' + id).removeClass('alert-info')
                                .addClass('alert-success')
                                .html('<i class="icon-ok"></i> ' +
                                    'Successfully saved ' +
                                    '“' + fileName + '”');
                        } else {
                            $('#file-' + id).removeClass('alert-info')
                                .addClass('alert-error')
                                .html('<i class="icon-exclamation-sign"></i> ' +
                                    'Error with ' +
                                    '“' + fileName + '”: ' +
                                    responseJSON.error);
                        }
                    },
                    onError: function(id, name, reason, xhr) {
                        $('#fubErrorAlert .message').text(reason);

                        $('#fubErrorAlert button').click(function() {
                            $('#fubErrorAlert').hide();
                        });

                        $('#fubErrorAlert').show();
                    }                
                }
            });
        });
    </script>


}

eMotive.Site/Views/Test/DictTest.cshtml
@using System.Web.Mvc.Html
@using eMotive.SCE.Controllers
@model TestController.DictTester
@{
    ViewBag.Title = "DictTest";
}

<h2>DictTest</h2>
@Html.Partial("_modelStateError")
@using (Html.BeginForm("DictTest", "Test", FormMethod.Post, new { @class = "form-horizontal" }))
{
    for (var i = 0; i < Model.SomeStuff.Count; i++)
    {
        switch (Model.SomeStuff[i].Type)
         {
             case TestController.FieldType.Text:
                    @Html.HiddenFor(n => Model.SomeStuff[i].Type) @Html.HiddenFor(n => Model.SomeStuff[i].Name) @Model.SomeStuff[i].Name @Html.TextBoxFor(n => Model.SomeStuff[i].Value) 
                    break;
                 case TestController.FieldType.DropDownList:
                    @Html.HiddenFor(n => Model.SomeStuff[i].Type) @Html.HiddenFor(n => Model.SomeStuff[i].Name) @Model.SomeStuff[i].Name @Html.DropDownListFor(n => n.SomeStuff[i].Value, new SelectList(Model.DropDowns[@Model.SomeStuff[i].Name], "Key", "Value", Model.SomeStuff[i].Value), "Select an option")
                    break;
                 default:
                    break;
         }
    }
    <button type="submit" class="btn btn-info">Submit</button>
}

eMotive.Site/Views/Test/Index.cshtml
@model eMotive.Models.Objects.Users.User

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Index</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>User</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Username)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Username)
            @Html.ValidationMessageFor(model => model.Username)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Forename)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Forename)
            @Html.ValidationMessageFor(model => model.Forename)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Surname)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Surname)
            @Html.ValidationMessageFor(model => model.Surname)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Email)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Email)
            @Html.ValidationMessageFor(model => model.Email)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Enabled)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Enabled)
            @Html.ValidationMessageFor(model => model.Enabled)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Archived)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Archived)
            @Html.ValidationMessageFor(model => model.Archived)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

eMotive.Site/Views/Test/Index2.cshtml
@model IEnumerable<eMotive.Models.Objects.Users.User>

@{
    ViewBag.Title = "Index2";
}

<h2>Index2</h2>

<p>
    @Html.ActionLink("Create New", "Index")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Username)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Forename)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Surname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Enabled)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Archived)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Username)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Forename)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Surname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Enabled)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Archived)
        </td>
    </tr>
}

</table>

eMotive.Site/Views/Test/ModalTest.cshtml
@{
    ViewBag.Title = "ModalTest";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>ModalTest</h2>

<button onclick="showError('this is a message', 'the Title'); return false;">Do Stuff</button>

@section Scripts
{
    <script>
        $(function () {
            Ajax.DoQuery(routes.URL("FetchAllRoles"), function (data) { alert(data.results); });
        });


    </script>
}

eMotive.Site/Views/Test/PDF.cshtml
@{
    ViewBag.Title = "PDF";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>PDF</h2>

eMotive.Site/Views/Test/PDFView.cshtml
@using eMotive.Models.Objects.Certificates
@model SCECertificate
@{
    ViewBag.Title = "PDFView";
}
<style>
    .certBody {
        font-family: Arial, Helvetica, sans-serif;
    }
    .entrySpacing {
        margin-top: 80px;
    }
</style>
<div class="certBody" style="margin: 100px;">
    <img src="~/Content/images/PdfCertificate/UoBLogo.jpg?width=130" style="float: left;" /> <img style="float: right; padding-top:15px;" src="~/Content/images/PdfCertificate/UoBLogoText.png?width=200" />
    <div style=" clear: right; float: right; padding-right: 38px;">
        College of Medical and<br/> 
        Dental Sciences<br/><br/>
        <b>Education Unit</b><br/>
        <span style="font-size: 13px;">Telephone: 0121 414 7402</span><br/>
    </div>
    <div style="clear: both;"></div>

    <h1 style="width: 390px; margin: 0 auto; margin-top: 80px;">Certificate of Attendance</h1>
    
    <p class="entrySpacing">This certificate confirms that <b style="padding-left:10px; font-size: 1.3em;">@Model.Title @Model.Forename @Model.Surname</b></p>
    <p class="entrySpacing">Grade <b style="padding-left:10px; font-size: 1.3em;">@Model.Grade</b></p>
    <p class="entrySpacing">Trust/Surgery <b style="padding-left:10px; font-size: 1.3em;">@Model.Trust</b></p>
    <p class="entrySpacing">Attended the meeting/course <b style="padding-left:10px; font-size: 1.3em;">Briefing for Year 4 Clinical Examiners</b></p>
    <span style="clear:both;"></span>
    <p class="entrySpacing">On <b style="padding-left:10px; font-size: 1.3em;">@Model.DateOfCourse</b></p>
    <p class="entrySpacing">RCP Activity Code Number: <b style="padding-left:10px; font-size: 1.3em;">@Model.RCPNumber</b></p>
    <b>‘Briefing for Year 3 Clinical Examiners' has been approved by the Federation of the Royal Colleges of Physicians of the United Kingdom for 3 category 1 (external) CPD credit(s).</b>
    <p class="entrySpacing">Course Organiser's signature: <img src="~/Content/images/PdfCertificate/BevSignature.png" /></p>
    <p>Date: <b style="padding-left:10px; font-size: 1.3em;">@Model.DateSigned</b></p>
</div>

eMotive.Site/Views/Test/SendSCEEmails.cshtml
@{
    ViewBag.Title = "SendSCEEmails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>SendSCEEmails</h2>

eMotive.Site/Views/Test/SignalRTest.cshtml
@{
    ViewBag.Title = "SignalRTest";
}

<h2>SignalRTest</h2>
<script src="~/Scripts/jquery-1.9.1.min.js" type="text/javascript"></script>
<script src="~/Scripts/jquery.signalR-2.1.1.min.js" type="text/javascript"></script>
<script src="~/signalr/hubs" type="text/javascript"></script>

<script>
    $(function() {
        var test = $.connection.MMIHub;
        
        test.client.doMessage = function(message) {
            alert(message);
        };


        $.connection.hub.start().done(function () {

            $("#btnTestA").click(function() {
                test.server.messageTestA("clicked me A!");
            });

            $("#btnTestB").click(function () {
                test.server.messageTestB("clicked me B!");
            });

            $("#btnGroupA").click(function () {
                test.server.joinGroup("GroupA");
                $("#btnGroupA").hide();
                $("#btnLeaveGroupA").show();
            });

            $("#btnGroupB").click(function () {
                test.server.joinGroup("GroupB");
                $("#btnGroupB").hide();
                $("#btnLeaveGroupB").show();
            });

            $("#btnLeaveGroupA").click(function () {
                test.server.leaveGroup("GroupA");
                $("#btnLeaveGroupA").hide();
                $("#btnGroupA").show();
            });

            $("#btnLeaveGroupB").click(function () {
                test.server.leaveGroup("GroupB");
                $("#btnLeaveGroupB").hide();
                $("#btnGroupB").show();
            });

        });
    });
</script>

<button id="btnTestA">tester A</button>
<button id="btnTestB">tester B</button><br/>


<button id="btnGroupA">Join Group A</button><button id="btnLeaveGroupA" style="display: none;">Leave Group A</button><br/>
<button id="btnGroupB">Join Group B</button><button id="btnLeaveGroupB" style="display: none;">Leave Group B</button>

eMotive.Site/Views/Test/UploadTest.cshtml
@{
    ViewBag.Title = "UploadTest";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<link href="~/Content/fineuploader-3.8.2.min.css" rel="stylesheet" />
  <style>
      .qq-upload-list {
        text-align: left;
      }

      /* For the bootstrapped demos */
      li.alert-success {
        background-color: #DFF0D8;
      }

      li.alert-error {
        background-color: #F2DEDE;
      }

      .alert-error .qq-upload-failed-text {
        display: inline;
      }
    </style>

<h2>UploadTest</h2>

<div id="fubErrorAlert" class="alert alert-error hide">
    <button type="button" class="close">&times;</button>
    <span class="message"></span>
</div>

<div id="fine-uploader-basic" class="btn btn-success">
  <i class="icon-upload icon-white"></i> Click to upload
</div>
<div id="messages"></div>


@section Scripts
{
    <script src="~/Scripts/fineuploader-3.8.2.min.js"></script>
    <script>
        $(document).ready(function() {
            var $fub = $('#fine-uploader-basic');
            var $messages = $('#messages');

            var uploader = new qq.FineUploaderBasic({
                button: $fub[0],
                multiple: false,
                request: {
                    endpoint: 'UploadFile'
                },
              //  validation: {
                  //  allowedExtensions: ['jpeg', 'jpg', 'gif', 'png'],
                 //   sizeLimit: 204800 // 200 kB = 200 * 1024 bytes
              //  },
                callbacks: {
                    onSubmit: function(id, fileName) {
                        $messages.append('<div id="file-' + id + '" class="alert" style="margin: 20px 0 0"></div>');
                    },
                    onUpload: function(id, fileName) {
                        $('#file-' + id).addClass('alert-info')
                            .html('<img src="client/loading.gif" alt="Initializing. Please hold."> ' +
                                'Initializing ' +
                                '“' + fileName + '”');
                    },
                    onProgress: function(id, fileName, loaded, total) {
                        if (loaded < total) {
                            progress = Math.round(loaded / total * 100) + '% of ' + Math.round(total / 1024) + ' kB';
                            $('#file-' + id).removeClass('alert-info')
                                .html('<img src="client/loading.gif" alt="In progress. Please hold."> ' +
                                    'Uploading ' +
                                    '“' + fileName + '” ' +
                                    progress);
                        } else {
                            $('#file-' + id).addClass('alert-info')
                                .html('<img src="client/loading.gif" alt="Saving. Please hold."> ' +
                                    'Saving ' +
                                    '“' + fileName + '”');
                        }
                    },
                    onComplete: function(id, fileName, responseJSON) {
                        if (responseJSON.success) {
                            $('#file-' + id).removeClass('alert-info')
                                .addClass('alert-success')
                                .html('<i class="icon-ok"></i> ' +
                                    'Successfully saved ' +
                                    '“' + fileName + '”' +
                                    '<br><img src="img/success.jpg" alt="' + fileName + '">');
                        } else {
                            $('#file-' + id).removeClass('alert-info')
                                .addClass('alert-error')
                                .html('<i class="icon-exclamation-sign"></i> ' +
                                    'Error with ' +
                                    '“' + fileName + '”: ' +
                                    responseJSON.error);
                        }
                    },
                    onError: function(id, name, reason, xhr) {
                        $('#fubErrorAlert .message').text(reason);

                        $('#fubErrorAlert button').click(function() {
                            $('#fubErrorAlert').hide();
                        });

                        $('#fubErrorAlert').show();
                    }                
                }
            });
        });
    </script>


}